### ISSUE TITLE
Google maps search result

### ISSUE THREAD

**Issue by yeehowe** [abbasali-io/careturn-issues#5]
![IMG_0529](https://github.com/user-attachments/assets/e521b428-7588-420c-9e8e-3cddaf0cb411)

Can set the search result to display Malaysia address only?

**Comment by abbasali-io** [comment]
The address picker that integrate with Google Map, is using the default API (not very expensive and a lot of free quota) in order to customize this behaviour, we ll have to create custom widgets with a different maps api version. 

I believe this can be incorporated in the future!

I am marking this post as the feature request for our records in the future and closing this issue.
